[tool.poetry]
name = "snowball"
version = "0.1.0"
description = ""
authors = ["Elven Lin, RetrO9 <elvenlin1998@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
